export const CREATE_FEEDBACK_REQUEST = "CREATE_FEEDBACK_REQUEST";
export const CREATE_FEEDBACK_SUCCESS = "CREATE_FEEDBACK_SUCCESS";
export const CREATE_FEEDBACK_RESET = " CREATE_FEEDBACK_RESET";
export const CREATE_FEEDBACK_FAIL = "CREATE_FEEDBACK_FAIL";

export const ALL_FEEDBACKS_REQUEST = "ALL_FEEDBACKS_REQUEST";
export const ALL_FEEDBACKS_SUCCESS = "ALL_FEEDBACKS_SUCCESS";
export const ALL_FEEDBACKS_FAIL = "ALL_FEEDBACKS_FAIL";

export const UPDATE_FEEDBACK_REQUEST = "UPDATE_FEEDBACK_REQUEST";
export const UPDATE_FEEDBACK_SUCCESS = "UPDATE_FEEDBACK_SUCCESS";
export const UPDATE_FEEDBACK_RESET = "UPDATE_FEEDBACK_RESET";
export const UPDATE_FEEDBACK_FAIL = "UPDATE_FEEDBACK_FAIL";

export const DELETE_FEEDBACK_REQUEST = "DELETE_FEEDBACK_REQUEST";
export const DELETE_FEEDBACK_SUCCESS = "DELETE_FEEDBACK_SUCCESS";
export const DELETE_FEEDBACK_RESET = "DELETE_FEEDBACK_RESET";
export const DELETE_FEEDBACK_FAIL = "DELETE_FEEDBACK_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
