export const ALL_NEWFEED_REQUEST = "ALL_NEWFEED_REQUEST";
export const ALL_NEWFEED_SUCCESS = "ALL_NEWFEED_SUCCESS";
export const ALL_NEWFEED_FAIL = "ALL_NEWFEED_FAIL";

export const ADMIN_NEWFEED_REQUEST = "ADMIN_NEWFEED_REQUEST";
export const ADMIN_NEWFEED_SUCCESS = "ADMIN_NEWFEED_SUCCESS";
export const ADMIN_NEWFEED_FAIL = "ADMIN_NEWFEED_FAIL";

export const NEW_NEWFEED_REQUEST = "NEW_NEWFEED_REQUEST";
export const NEW_NEWFEED_SUCCESS = "NEW_NEWFEED_SUCCESS";
export const NEW_NEWFEED_RESET = "NEW_NEWFEED_RESET";
export const NEW_NEWFEED_FAIL = "NEW_NEWFEED_FAIL";

export const UPDATE_NEWFEED_REQUEST = "UPDATE_NEWFEED_REQUEST";
export const UPDATE_NEWFEED_SUCCESS = "UPDATE_NEWFEED_SUCCESS";
export const UPDATE_NEWFEED_RESET = "UPDATE_NEWFEED_RESET";
export const UPDATE_NEWFEED_FAIL = "UPDATE_NEWFEED_FAIL";

export const DELETE_NEWFEED_REQUEST = "DELETE_NEWFEED_REQUEST";
export const DELETE_NEWFEED_SUCCESS = "DELETE_NEWFEED_SUCCESS";
export const DELETE_NEWFEED_RESET = "DELETE_NEWFEED_RESET";
export const DELETE_NEWFEED_FAIL = "DELETE_NEWFEED_FAIL";

export const NEWFEED_DETAILS_REQUEST = "NEWFEED_DETAILS_REQUEST";
export const NEWFEED_DETAILS_SUCCESS = "NEWFEED_DETAILS_SUCCESS";
export const NEWFEED_DETAILS_FAIL = "NEWFEED_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
