export const ADMIN_STATISTICAL_REQUEST = "ADMIN_STATISTICAL_REQUEST";
export const ADMIN_STATISTICAL_SUCCESS = "ADMIN_STATISTICAL_SUCCESS";
export const ADMIN_STATISTICAL_FAIL = "ADMIN_STATISTICAL_FAIL";

export const NEW_STATISTICAL_REQUEST = "NEW_STATISTICAL_REQUEST";
export const NEW_STATISTICAL_SUCCESS = "NEW_STATISTICAL_SUCCESS";
export const NEW_STATISTICAL_RESET = "NEW_STATISTICAL_RESET";
export const NEW_STATISTICAL_FAIL = "NEW_STATISTICAL_FAIL";

export const DELETE_STATISTICAL_REQUEST = "DELETE_STATISTICAL_REQUEST";
export const DELETE_STATISTICAL_SUCCESS = "DELETE_STATISTICAL_SUCCESS";
export const DELETE_STATISTICAL_RESET = "DELETE_STATISTICAL_RESET";
export const DELETE_STATISTICAL_FAIL = "DELETE_STATISTICAL_FAIL";

export const STATISTICAL_DETAILS_REQUEST = "STATISTICAL_DETAILS_REQUEST";
export const STATISTICAL_DETAILS_SUCCESS = "STATISTICAL_DETAILS_SUCCESS";
export const STATISTICAL_DETAILS_FAIL = "STATISTICAL_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
