export const CREATE_SUPPLIER_REQUEST = "CREATE_SUPPLIER_REQUEST";
export const CREATE_SUPPLIER_SUCCESS = "CREATE_SUPPLIER_SUCCESS";
export const CREATE_SUPPLIER_RESET = " CREATE_SUPPLIER_RESET";
export const CREATE_SUPPLIER_FAIL = "CREATE_SUPPLIER_FAIL";

export const ALL_SUPPLIERS_REQUEST = "ALL_SUPPLIERS_REQUEST";
export const ALL_SUPPLIERS_SUCCESS = "ALL_SUPPLIERS_SUCCESS";
export const ALL_SUPPLIERS_FAIL = "ALL_SUPPLIERS_FAIL";

export const UPDATE_SUPPLIER_REQUEST = "UPDATE_SUPPLIER_REQUEST";
export const UPDATE_SUPPLIER_SUCCESS = "UPDATE_SUPPLIER_SUCCESS";
export const UPDATE_SUPPLIER_RESET = "UPDATE_SUPPLIER_RESET";
export const UPDATE_SUPPLIER_FAIL = "UPDATE_SUPPLIER_FAIL";

export const DELETE_SUPPLIER_REQUEST = "DELETE_SUPPLIER_REQUEST";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
export const DELETE_SUPPLIER_RESET = "DELETE_SUPPLIER_RESET";
export const DELETE_SUPPLIER_FAIL = "DELETE_SUPPLIER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
